# ✅ NumPy Practice Exercise 1: Complete Solutions & Explanations

Here are the complete, step-by-step solutions for the **20 problems** in `02_numpy_exercise_1.ipynb`.


### Problem 1: Import NumPy and Check Version

**Question:** Import NumPy using the standard alias `np` and print the installed version.


In [1]:
import numpy as np
print("NumPy version:", np.__version__)


NumPy version: 2.5.3


### Problem 2: Create a 1D Array with Integer Range

**Question:** Create a 1D array of integers from 10 to 49 (inclusive).


In [2]:
arr = np.arange(10, 50)
print("Shape:", arr.shape)
print("First 5:", arr[:5])
print("Last 5:", arr[-5:])


Shape: (40,)
First 5: [10 11 12 13 14]
Last 5: [45 46 47 48 49]


### Problem 3: Reverse an Array

**Question:** Reverse the 1D array created in Problem 2 using slicing (no loops or functions).


In [3]:
arr = np.arange(10, 50)
reversed_arr = arr[::-1]
print("First 5 of reversed:", reversed_arr[:5])
print("Last 5 of reversed:", reversed_arr[-5:])


First 5 of reversed: [49 48 47 46 45]
Last 5 of reversed: [14 13 12 11 10]


### Problem 4: Create an Identity Matrix with Specific Dtype

**Question:** Create a 3x3 identity matrix where each element is a 32-bit floating point (`float32`).


In [4]:
identity = np.eye(3, dtype=np.float32)
print(identity)
print("dtype:", identity.dtype)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
dtype: float32


### Problem 5: Evenly Spaced Points (Linspace)

**Question:** Create a 1D array of 30 evenly spaced numbers between 0 and 1 (inclusive). Print the step size between consecutive elements.


In [5]:
pts, step = np.linspace(0, 1, 30, retstep=True)
print(pts)
print("Step size between elements:", step)


[0.         0.03448276 0.06896552 0.10344828 0.13793103 0.17241379
 0.20689655 0.24137931 0.27586207 0.31034483 0.34482759 0.37931034
 0.4137931  0.44827586 0.48275862 0.51724138 0.55172414 0.5862069
 0.62068966 0.65517241 0.68965517 0.72413793 0.75862069 0.79310345
 0.82758621 0.86206897 0.89655172 0.93103448 0.96551724 1.        ]
Step size between elements: 0.034482758620689655


### Problem 6: Construct a Diagonal Matrix with Offset

**Question:** Create a 5x5 matrix with values `[1, 2, 3, 4]` positioned immediately below the main diagonal (offset k = -1).


In [6]:
diag_mat = np.diag([1, 2, 3, 4], k=-1)
print(diag_mat)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### Problem 7: Standard Normal Matrix & Aggregate Statistics

**Question:** Using `np.random.default_rng(42)`, generate an 8x8 matrix drawn from a standard normal distribution. Compute and print its:
- Minimum value
- Maximum value
- Mean
- Standard Deviation


In [7]:
rng = np.random.default_rng(42)
mat = rng.standard_normal((8, 8))
print(f"Min:  {mat.min():.4f}")
print(f"Max:  {mat.max():.4f}")
print(f"Mean: {mat.mean():.4f}")
print(f"Std:  {mat.std():.4f}")


Min:  -1.9510
Max:  2.1416
Mean: 0.0414
Std:  0.7894


### Problem 8: Replace Odd Numbers Without Modifying Original

**Question:** Given `arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])`, create a new array `out` where all odd numbers are replaced with -1, while leaving `arr` untouched.


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
out = np.where(arr % 2 != 0, -1, arr)
print("Original:", arr)
print("Replaced:", out)


Original: [ 1  2  3  4  5  6  7  8  9 10]
Replaced: [-1  2 -1  4 -1  6 -1  8 -1 10]


### Problem 9: Multi-Dimensional Slicing & Shapes

**Question:** Given `mat = np.arange(36).reshape(6, 6)`, extract:
1. The 4 corner elements as a (2, 2) array.
2. The inner 4x4 matrix (excluding border rows and columns).
3. The 3rd column, but keeping its shape as (6, 1) rather than (6,).


In [9]:
mat = np.arange(36).reshape(6, 6)
print("Original 6x6:\n", mat)

# 1. Four corners
corners = mat[::5, ::5]
print("\n1. Corners (2x2):\n", corners)

# 2. Inner 4x4
inner = mat[1:-1, 1:-1]
print("\n2. Inner 4x4:\n", inner)

# 3. 3rd column as (6, 1)
col_3 = mat[:, 2:3]
print("\n3. Column 2 with kept shape:\n", col_3, "\nShape:", col_3.shape)


Original 6x6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

1. Corners (2x2):
 [[ 0  5]
 [30 35]]

2. Inner 4x4:
 [[ 7  8  9 10]
 [13 14 15 16]
 [19 20 21 22]
 [25 26 27 28]]

3. Column 2 with kept shape:
 [[ 2]
 [ 8]
 [14]
 [20]
 [26]
 [32]] 
Shape: (6, 1)


### Problem 10: Create an 8x8 Checkerboard Pattern

**Question:** Create an 8x8 matrix filled with 0s and 1s arranged in a checkerboard pattern (where 0 and 1 alternate both horizontally and vertically) using slicing and striding.


In [10]:
board = np.zeros((8, 8), dtype=int)
board[1::2, ::2] = 1
board[::2, 1::2] = 1
print("8x8 Checkerboard:\n", board)


8x8 Checkerboard:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem 11: Find Common Elements and Matching Positions

**Question:** Given two arrays:
`a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])`
`b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])`
1. Find the common unique elements between `a` and `b`.
2. Find the index positions where elements of `a` and `b` match exactly.


In [11]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# 1. Common elements
common = np.intersect1d(a, b)
print("Common elements:", common)

# 2. Matching positions
matching_idx = np.where(a == b)[0]
print("Matching positions:", matching_idx)


Common elements: [2 4]
Matching positions: [1 3 5 7]


### Problem 12: Filter Array with Multiple Conditions

**Question:** Given `x = np.array([1, 5, 10, 15, 20, 25, 30, 35, 40])`, extract all values that are between 10 and 30 (inclusive) and strictly divisible by 5.


In [12]:
x = np.array([1, 5, 10, 15, 20, 25, 30, 35, 40])
filtered = x[(x >= 10) & (x <= 30) & (x % 5 == 0)]
print("Filtered:", filtered)


Filtered: [10 15 20 25 30]


### Problem 13: Swap Rows in a 2D Matrix

**Question:** Given `mat = np.arange(16).reshape(4, 4)`, swap row 0 and row 2 in-place or via index reordering.


In [13]:
mat = np.arange(16).reshape(4, 4)
print("Before swap:\n", mat)

# Swapping row 0 and row 2
mat[[0, 2]] = mat[[2, 0]]
print("\nAfter swap:\n", mat)


Before swap:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

After swap:
 [[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]
 [12 13 14 15]]


### Problem 14: Column-Wise Mean Subtraction (Broadcasting)

**Question:** Given a 5x3 matrix with random floats, subtract each column's mean from the corresponding column so that each resulting column has a mean of 0. Verify the result.


In [14]:
rng = np.random.default_rng(0)
X = rng.uniform(10, 50, size=(5, 3))
print("Original matrix:\n", np.round(X, 2))

# Compute column means: shape (3,) broadcasts across 5 rows
col_means = np.mean(X, axis=0)
X_centered = X - col_means
print("\nCentered matrix:\n", np.round(X_centered, 2))
print("New column means (should be ~0):", np.round(np.mean(X_centered, axis=0), 5))


Original matrix:
 [[35.48 20.79 11.64]
 [10.66 42.53 46.51]
 [34.27 39.18 31.74]
 [47.4  42.63 10.11]
 [44.3  11.34 39.19]]

Centered matrix:
 [[  1.06 -10.5  -16.2 ]
 [-23.76  11.23  18.67]
 [ -0.16   7.88   3.91]
 [ 12.98  11.34 -17.73]
 [  9.88 -19.95  11.35]]
New column means (should be ~0): [0. 0. 0.]


### Problem 15: Replace the Maximum Value with Zero

**Question:** Given a 1D array of 10 random numbers between 0 and 1, find the index of the maximum value using `argmax()` and set that value to 0.


In [15]:
rng = np.random.default_rng(123)
v = rng.random(10)
print("Original:", np.round(v, 3))

max_idx = np.argmax(v)
print(f"Max value {v[max_idx]:.3f} at index {max_idx}")
v[max_idx] = 0.0
print("After zeroing max:", np.round(v, 3))


Original: [0.682 0.054 0.22  0.184 0.176 0.812 0.923 0.277 0.82  0.89 ]
Max value 0.923 at index 6
After zeroing max: [0.682 0.054 0.22  0.184 0.176 0.812 0.    0.277 0.82  0.89 ]


### Problem 16: Find Mode and Frequency using `np.unique`

**Question:** Given `arr = np.array([4, 2, 7, 2, 5, 2, 9, 7, 7, 7, 3, 1, 7])`, find the most frequently occurring element (the mode) and its frequency using `np.unique`.


In [16]:
arr = np.array([4, 2, 7, 2, 5, 2, 9, 7, 7, 7, 3, 1, 7])
vals, counts = np.unique(arr, return_counts=True)
mode_idx = np.argmax(counts)
print(f"Mode: {vals[mode_idx]} (occurred {counts[mode_idx]} times)")


Mode: 7 (occurred 5 times)


### Problem 17: Flattening: View vs Copy Demonstration

**Question:** Create a 3x3 matrix. Obtain a 1D version using `ravel()` and another using `flatten()`. Modify the first element of both. Observe and explain which one altered the original matrix.


In [17]:
orig = np.arange(1, 10).reshape(3, 3)
print("Original:\n", orig)

rav = orig.ravel()
flat = orig.flatten()

rav[0] = 999
flat[1] = 888

print("\nOriginal after modifying rav[0] and flat[1]:\n", orig)
print("\nExplanation: ravel() returns a VIEW (sharing memory buffer), so orig[0,0] changed to 999. flatten() returns a new COPY, so flat[1] mutation had no effect on orig.")


Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Original after modifying rav[0] and flat[1]:
 [[999   2   3]
 [  4   5   6]
 [  7   8   9]]

Explanation: ravel() returns a VIEW (sharing memory buffer), so orig[0,0] changed to 999. flatten() returns a new COPY, so flat[1] mutation had no effect on orig.


### Problem 18: Stacking Arrays Horizontally, Vertically and Depth-wise

**Question:** Given `A = np.arange(4).reshape(2, 2)` and `B = np.ones((2, 2))`, produce:
1. Vertical stack `(4, 2)`
2. Horizontal stack `(2, 4)`
3. Depth-wise stack `(2, 2, 2)`


In [18]:
A = np.arange(4).reshape(2, 2)
B = np.ones((2, 2))

print("1. Vertical Stack:\n", np.vstack([A, B]))
print("\n2. Horizontal Stack:\n", np.hstack([A, B]))
print("\n3. Depth Stack Shape:", np.dstack([A, B]).shape)


1. Vertical Stack:
 [[0. 1.]
 [2. 3.]
 [1. 1.]
 [1. 1.]]

2. Horizontal Stack:
 [[0. 1. 1. 1.]
 [2. 3. 1. 1.]]

3. Depth Stack Shape: (2, 2, 2)


### Problem 19: Cumulative Sum and Product Along Axes

**Question:** Given `M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`, compute:
1. Cumulative sum down columns (axis=0).
2. Cumulative product across rows (axis=1).


In [19]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("1. Cumulative sum down columns (axis=0):\n", np.cumsum(M, axis=0))
print("\n2. Cumulative product across rows (axis=1):\n", np.cumprod(M, axis=1))


1. Cumulative sum down columns (axis=0):
 [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]

2. Cumulative product across rows (axis=1):
 [[  1   2   6]
 [  4  20 120]
 [  7  56 504]]


### Problem 20: Vectorized Value Clipping

**Question:** Given `arr = np.array([-2.5, -0.5, 0.2, 1.8, -1.2, 0.9, 2.3])`, clip all values to the range `[-1.0, 1.0]`:
1. Using boolean masking / indexing.
2. Using `np.clip`.
Verify both yield identical results.


In [20]:
arr = np.array([-2.5, -0.5, 0.2, 1.8, -1.2, 0.9, 2.3])

# Method 1: Boolean masking
c1 = arr.copy()
c1[c1 < -1.0] = -1.0
c1[c1 > 1.0] = 1.0

# Method 2: np.clip
c2 = np.clip(arr, -1.0, 1.0)

print("Method 1 (Masking):", c1)
print("Method 2 (np.clip):", c2)
print("Are they identical?", np.array_equal(c1, c2))


Method 1 (Masking): [-1.  -0.5  0.2  1.  -1.   0.9  1. ]
Method 2 (np.clip): [-1.  -0.5  0.2  1.  -1.   0.9  1. ]
Are they identical? True
